In [2]:
# 1. Assign your Name to variable name and Age to variable age. Make a Python program that prints your name and age.

In [6]:
name = "Ishaan Pare"
age = 20

print(f"Name: {name}, Age: {age}")

Name: Ishaan Pare, Age: 20


In [7]:
# 2. X="Datascience is used to extract meaningful insights." Split the string

In [8]:
X = "Datascience is used to extract meaningful insights."

arr = X.split(" ")
print(arr)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


In [ ]:
# 3. Make a function that gives multiplication of two numbers

In [9]:
def multiply(a, b):
    return a*b

print(multiply(53,34))

1802


In [10]:
# 4. Create a Dictionary of 5 States with their capitals. also print the keys and values.

In [12]:
data = {"Tamil Nadu": "Chennai", "Karnataka": "Bangaluru", "Uttrakhand": "Dehradun", "Madhya Prades": "Bhopal", "Arunachal Pradesh": "Itanagar"}

print(data.keys())
print(data.values())

dict_keys(['Tamil Nadu', 'Karnataka', 'Uttrakhand', 'Madhya Prades', 'Arunachal Pradesh'])
dict_values(['Chennai', 'Bangaluru', 'Dehradun', 'Bhopal', 'Itanagar'])


In [13]:
# 5. Create a list of 1000 numbers using range function.

In [20]:
num = [int(x) for x in range(1000)]
print(" ".join([str(x) for x in num[:20]]),".... 999")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 .... 999


In [21]:
# 6. Create an identity matrix of dimension 4 by 4

In [34]:
import numpy as np

In [39]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
# 7. Create a 3x3 matrix with values ranging from 1 to 9

In [47]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
# 8. Create 2 similar dimensional array and perform sum on them.

In [52]:
arr1 = np.arange(1,11).reshape((2,5))
arr2 = np.arange(12,22).reshape((2,5))
arr1+arr2

array([[13, 15, 17, 19, 21],
       [23, 25, 27, 29, 31]])

In [53]:
# 9. Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)

In [16]:
import pandas as pd

dt1 = pd.date_range("2023-02-01", "2023-03-01")
print(dt1)

DatetimeIndex(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
               '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
               '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28',
               '2023-03-01'],
              dtype='datetime64[ns]', freq='D')


In [55]:
# 10. Given a dictionary, convert it into corresponding dataframe and display it dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}

In [19]:
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}

df = pd.DataFrame(dictionary)
df

Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240